Update lab4.py
Pushed on 09/02/2022 at 15:41. error raised



16:59:16.221: [220] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false push --progress --porcelain origin refs/heads/main:main
error: failed to push some refs to 'https://github.com/Carson3822/220.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
To https://github.com/Carson3822/220.git
!	refs/heads/main:refs/heads/main	[rejected] (non-fast-forward)
hint: 'git pull ...') before pushing again.
Done
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
16:59:18.075: [220] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false fetch origin --recurse-submodules=no --progress --prune
16:59:18.515: [220] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false push --progress --porcelain origin refs/heads/main:main
error: failed to push some refs to 'https://github.com/Carson3822/220.git'
hint: Updates were rejected because the tip of your current branch is behind
To https://github.com/Carson3822/220.git
!	refs/heads/main:refs/heads/main	[rejected] (non-fast-forward)
hint: its remote counterpart. Integrate the remote changes (e.g.
Done
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
16:59:19.521: [220] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false fetch origin --recurse-submodules=no --progress --prune
16:59:19.914: [220] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false push --progress --porcelain origin refs/heads/main:main
error: failed to push some refs to 'https://github.com/Carson3822/220.git'
hint: Updates were rejected because the tip of your current branch is behind
To https://github.com/Carson3822/220.git
hint: its remote counterpart. Integrate the remote changes (e.g.
!	refs/heads/main:refs/heads/main	[rejected] (non-fast-forward)
hint: 'git pull ...') before pushing again.
Done
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
16:59:20.891: [220] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false fetch origin --recurse-submodules=no --progress --prune
16:59:21.259: [220] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false push --progress --porcelain origin refs/heads/main:main
error: failed to push some refs to 'https://github.com/Carson3822/220.git'
hint: Updates were rejected because the tip of your current branch is behind
To https://github.com/Carson3822/220.git
hint: its remote counterpart. Integrate the remote changes (e.g.
!	refs/heads/main:refs/heads/main	[rejected] (non-fast-forward)
hint: 'git pull ...') before pushing again.
Done
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
16:59:22.227: [220] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false fetch origin --recurse-submodules=no --progress --prune
16:59:22.608: [220] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false push --progress --porcelain origin refs/heads/main:main
error: failed to push some refs to 'https://github.com/Carson3822/220.git'
hint: Updates were rejected because the tip of your current branch is behind
To https://github.com/Carson3822/220.git
hint: its remote counterpart. Integrate the remote changes (e.g.
!	refs/heads/main:refs/heads/main	[rejected] (non-fast-forward)
hint: 'git pull ...') before pushing again.
Done
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
16:59:23.558: [220] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false fetch origin --recurse-submodules=no --progress --prune
16:59:23.914: [220] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false push --progress --porcelain origin refs/heads/main:main
error: failed to push some refs to 'https://github.com/Carson3822/220.git'
hint: Updates were rejected because the tip of your current branch is behind
To https://github.com/Carson3822/220.git
hint: its remote counterpart. Integrate the remote changes (e.g.
!	refs/heads/main:refs/heads/main	[rejected] (non-fast-forward)
hint: 'git pull ...') before pushing again.
Done
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
16:59:24.894: [220] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false fetch origin --recurse-submodules=no --progress --prune
16:59:25.260: [220] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false push --progress --porcelain origin refs/heads/main:main
error: failed to push some refs to 'https://github.com/Carson3822/220.git'
hint: Updates were rejected because the tip of your current branch is behind
To https://github.com/Carson3822/220.git
hint: its remote counterpart. Integrate the remote changes (e.g.
!	refs/heads/main:refs/heads/main	[rejected] (non-fast-forward)
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
Done
16:59:26.227: [220] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false fetch origin --recurse-submodules=no --progress --prune
16:59:26.589: [220] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false push --progress --porcelain origin refs/heads/main:main
error: failed to push some refs to 'https://github.com/Carson3822/220.git'
hint: Updates were rejected because the tip of your current branch is behind
To https://github.com/Carson3822/220.git
hint: its remote counterpart. Integrate the remote changes (e.g.
!	refs/heads/main:refs/heads/main	[rejected] (non-fast-forward)
hint: 'git pull ...') before pushing again.
Done
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
16:59:27.631: [220] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false fetch origin --recurse-submodules=no --progress --prune
16:59:27.993: [220] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false push --progress --porcelain origin refs/heads/main:main
error: failed to push some refs to 'https://github.com/Carson3822/220.git'
hint: Updates were rejected because the tip of your current branch is behind
To https://github.com/Carson3822/220.git
!	refs/heads/main:refs/heads/main	[rejected] (non-fast-forward)
hint: its remote counterpart. Integrate the remote changes (e.g.
Done
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
16:59:28.943: [220] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false fetch origin --recurse-submodules=no --progress --prune
16:59:29.313: [220] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false push --progress --porcelain origin refs/heads/main:main
error: failed to push some refs to 'https://github.com/Carson3822/220.git'
hint: Updates were rejected because the tip of your current branch is behind
To https://github.com/Carson3822/220.git
hint: its remote counterpart. Integrate the remote changes (e.g.
!	refs/heads/main:refs/heads/main	[rejected] (non-fast-forward)
hint: 'git pull ...') before pushing again.
Done
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
16:59:30.385: [220] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false fetch origin --recurse-submodules=no --progress --prune